package ruokaVinkki.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import java.util.*;
import ruokaVinkki.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.11.11 19:03:45 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AinesosatTest {



  // Generated by ComTest BEGIN
  /** testAnnaAinesosat62 */
  @Test
  public void testAnnaAinesosat62() {    // Ainesosat: 62
    Ainesosat ainesosat = new Ainesosat(); 
    Ainesosa maito = new Ainesosa(1); ainesosat.lisaa(maito); 
    Ainesosa hiiva = new Ainesosa(2); ainesosat.lisaa(hiiva); 
    List<Ainesosa> loydetyt; 
    int[] reseptienAinesosat = { 1, 2} ; 
    loydetyt = ainesosat.annaAinesosat(reseptienAinesosat); 
    assertEquals("From: Ainesosat line: 70", 2, loydetyt.size()); 
  } // Generated by ComTest END
}