package ruokaVinkki.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import ruokaVinkki.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.11.11 17:39:54 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AinesosaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi41 */
  @Test
  public void testRekisteroi41() {    // Ainesosa: 41
    Ainesosa maito = new Ainesosa(); 
    assertEquals("From: Ainesosa line: 43", 0, maito.getAinesosaId()); 
    maito.rekisteroi(); 
    Ainesosa hiiva = new Ainesosa(); 
    hiiva.rekisteroi(); 
    int n1 = maito.getAinesosaId(); 
    int n2 = hiiva.getAinesosaId(); 
    assertEquals("From: Ainesosa line: 49", n2-1, n1); 
  } // Generated by ComTest END
}