package ruokaVinkki.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import ruokaVinkki.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.11.11 17:03:51 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ReseptitTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa34 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa34() throws SailoException {    // Reseptit: 34
    Reseptit reseptit = new Reseptit(); 
    Resepti mikropitsa = new Resepti(); 
    Resepti makaroni = new Resepti(); 
    reseptit.lisaa(mikropitsa); assertEquals("From: Reseptit line: 39", 1, reseptit.getLkm()); 
    reseptit.lisaa(makaroni); assertEquals("From: Reseptit line: 40", 2, reseptit.getLkm()); 
    assertEquals("From: Reseptit line: 41", mikropitsa, reseptit.anna(0)); 
    assertEquals("From: Reseptit line: 42", makaroni, reseptit.anna(1)); 
    try {
    assertEquals("From: Reseptit line: 43", mikropitsa, reseptit.anna(2)); 
    fail("Reseptit: 43 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    reseptit.lisaa(mikropitsa); assertEquals("From: Reseptit line: 44", 3, reseptit.getLkm()); 
    reseptit.lisaa(mikropitsa); assertEquals("From: Reseptit line: 45", 4, reseptit.getLkm()); 
    reseptit.lisaa(mikropitsa); assertEquals("From: Reseptit line: 46", 5, reseptit.getLkm()); 
    try {
    reseptit.lisaa(mikropitsa); 
    fail("Reseptit: 47 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}