package ruokaVinkki.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import ruokaVinkki.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.11.29 16:42:21 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ReseptitTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa42 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa42() throws SailoException {    // Reseptit: 42
    Reseptit reseptit = new Reseptit(); 
    Resepti mikropitsa = new Resepti(); 
    Resepti makaroni = new Resepti(); 
    reseptit.lisaa(mikropitsa); assertEquals("From: Reseptit line: 47", 1, reseptit.getLkm()); 
    reseptit.lisaa(makaroni); assertEquals("From: Reseptit line: 48", 2, reseptit.getLkm()); 
    assertEquals("From: Reseptit line: 49", mikropitsa, reseptit.anna(0)); 
    assertEquals("From: Reseptit line: 50", makaroni, reseptit.anna(1)); 
    try {
    assertEquals("From: Reseptit line: 51", mikropitsa, reseptit.anna(2)); 
    fail("Reseptit: 51 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    reseptit.lisaa(mikropitsa); assertEquals("From: Reseptit line: 52", 3, reseptit.getLkm()); 
    reseptit.lisaa(mikropitsa); assertEquals("From: Reseptit line: 53", 4, reseptit.getLkm()); 
    reseptit.lisaa(mikropitsa); assertEquals("From: Reseptit line: 54", 5, reseptit.getLkm()); 
    reseptit.lisaa(mikropitsa); 
  } // Generated by ComTest END
}