package ruokaVinkki.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import ruokaVinkki.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.11.29 16:25:38 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ReseptiTest {



  // Generated by ComTest BEGIN
  /** testGetNimi31 */
  @Test
  public void testGetNimi31() {    // Resepti: 31
    Resepti nakkijuustosarvet = new Resepti(); 
    nakkijuustosarvet.testiResepti(); 
    assertEquals("From: Resepti line: 34", "Nakki-juustosarvet", nakkijuustosarvet.getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi61 */
  @Test
  public void testRekisteroi61() {    // Resepti: 61
    Resepti mikropitsa = new Resepti(); 
    assertEquals("From: Resepti line: 63", 0, mikropitsa.getReseptiId()); 
    mikropitsa.rekisteroi(); 
    Resepti makaroni = new Resepti(); 
    makaroni.rekisteroi(); 
    int n1 = mikropitsa.getReseptiId(); 
    int n2 = makaroni.getReseptiId(); 
    assertEquals("From: Resepti line: 69", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString92 */
  @Test
  public void testToString92() {    // Resepti: 92
    Resepti mikropitsa = new Resepti(); 
    mikropitsa.parse("1|Mikropitsa|2 min| Laita mikropitsa mikroon."); 
    assertEquals("From: Resepti line: 95", true, mikropitsa.toString().startsWith("1|Mikropitsa|2 min")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse110 */
  @Test
  public void testParse110() {    // Resepti: 110
    Resepti mikropitsa = new Resepti(); 
    mikropitsa.parse("1|Mikropitsa|2 min| Laita mikropitsa mikroon."); 
    assertEquals("From: Resepti line: 113", true, mikropitsa.toString().startsWith("1|Mikropitsa|2 min")); 
    mikropitsa.rekisteroi(); 
    int n = mikropitsa.getReseptiId(); 
    mikropitsa.parse(""+(n+20));  // Otetaan merkkijonosta vain tunnusnumero
    mikropitsa.rekisteroi();  // ja tarkistetaan että seuraavalla kertaa tulee yhtä isompi
    assertEquals("From: Resepti line: 118", n+20+1, mikropitsa.getReseptiId()); 
  } // Generated by ComTest END
}