package ruokaVinkki.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import java.util.*;
import ruokaVinkki.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.11.11 23:02:29 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ReseptienAinesosatTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa36 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa36() throws SailoException {    // ReseptienAinesosat: 36
    ReseptienAinesosat reseptienAinesosat = new ReseptienAinesosat(); 
    ReseptinAinesosa maito = new ReseptinAinesosa(); 
    maito.testiReseptinAinesosa(); 
    ReseptinAinesosa hiiva = new ReseptinAinesosa(); 
    reseptienAinesosat.lisaa(maito); assertEquals("From: ReseptienAinesosat line: 42", 1, reseptienAinesosat.getLkm()); 
    reseptienAinesosat.lisaa(hiiva); assertEquals("From: ReseptienAinesosat line: 43", 2, reseptienAinesosat.getLkm()); 
    assertEquals("From: ReseptienAinesosat line: 44", maito, reseptienAinesosat.anna(0)); 
    assertEquals("From: ReseptienAinesosat line: 45", hiiva, reseptienAinesosat.anna(1)); 
    try {
    assertEquals("From: ReseptienAinesosat line: 46", maito, reseptienAinesosat.anna(2)); 
    fail("ReseptienAinesosat: 46 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    reseptienAinesosat.lisaa(maito); assertEquals("From: ReseptienAinesosat line: 47", 3, reseptienAinesosat.getLkm()); 
    reseptienAinesosat.lisaa(maito); assertEquals("From: ReseptienAinesosat line: 48", 4, reseptienAinesosat.getLkm()); 
    reseptienAinesosat.lisaa(maito); assertEquals("From: ReseptienAinesosat line: 49", 5, reseptienAinesosat.getLkm()); 
    try {
    reseptienAinesosat.lisaa(maito); 
    fail("ReseptienAinesosat: 50 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaReseptinAinesosat75 */
  @Test
  public void testAnnaReseptinAinesosat75() {    // ReseptienAinesosat: 75
    ReseptienAinesosat reseptienAinesosat = new ReseptienAinesosat(); 
    ReseptinAinesosa maito = new ReseptinAinesosa(); 
    maito.testiReseptinAinesosa(); 
    ReseptinAinesosa hiiva = new ReseptinAinesosa(); 
    ReseptinAinesosa maito2 = new ReseptinAinesosa(); 
    maito2.testiReseptinAinesosa(); 
    try {
    reseptienAinesosat.lisaa(maito); 
    reseptienAinesosat.lisaa(hiiva); 
    reseptienAinesosat.lisaa(maito2); 
    } catch (SailoException ex) {
    System.out.println(ex.getMessage()); 
    }
    int[] t = reseptienAinesosat.annaReseptinAinesosat(1); 
    assertEquals("From: ReseptienAinesosat line: 91", "[1, 1]", Arrays.toString(t)); 
  } // Generated by ComTest END
}