package ruokaVinkki.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import ruokaVinkki.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.11.11 16:24:21 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ReseptiTest {



  // Generated by ComTest BEGIN
  /** testGetNimi28 */
  @Test
  public void testGetNimi28() {    // Resepti: 28
    Resepti mikropitsa = new Resepti(); 
    mikropitsa.testiResepti(); 
    assertEquals("From: Resepti line: 31", "Mikropitsa", mikropitsa.getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi42 */
  @Test
  public void testRekisteroi42() {    // Resepti: 42
    Resepti mikropitsa = new Resepti(); 
    assertEquals("From: Resepti line: 44", 0, mikropitsa.getReseptiId()); 
    mikropitsa.rekisteroi(); 
    Resepti makaroni = new Resepti(); 
    makaroni.rekisteroi(); 
    int n1 = mikropitsa.getReseptiId(); 
    int n2 = makaroni.getReseptiId(); 
    assertEquals("From: Resepti line: 50", n2-1, n1); 
  } // Generated by ComTest END
}