package ruokaVinkki.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import ruokaVinkki.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.11.29 16:51:24 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ReseptinAinesosaTest {



  // Generated by ComTest BEGIN
  /** testToString48 */
  @Test
  public void testToString48() {    // ReseptinAinesosa: 48
    ReseptinAinesosa maito = new ReseptinAinesosa(); 
    maito.parse("1|1|2 1/2 dl"); 
    assertEquals("From: ReseptinAinesosa line: 51", true, maito.toString().startsWith("1|1|2 1/2 dl")); 
  } // Generated by ComTest END
}