package ruokaVinkki.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import java.util.*;
import ruokaVinkki.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.11.29 17:22:49 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ReseptienAinesosatTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa38 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa38() throws SailoException {    // ReseptienAinesosat: 38
    ReseptienAinesosat reseptienAinesosat1 = new ReseptienAinesosat(); 
    assertEquals("From: ReseptienAinesosat line: 41", 0, reseptienAinesosat1.getLkm()); 
    ReseptinAinesosa maito = new ReseptinAinesosa(); 
    maito.testiReseptinAinesosa(); 
    ReseptinAinesosa hiiva = new ReseptinAinesosa(); 
    reseptienAinesosat1.lisaa(maito); assertEquals("From: ReseptienAinesosat line: 45", 1, reseptienAinesosat1.getLkm()); 
    reseptienAinesosat1.lisaa(hiiva); assertEquals("From: ReseptienAinesosat line: 46", 2, reseptienAinesosat1.getLkm()); 
    assertEquals("From: ReseptienAinesosat line: 47", maito, reseptienAinesosat1.anna(0)); 
    assertEquals("From: ReseptienAinesosat line: 48", hiiva, reseptienAinesosat1.anna(1)); 
    try {
    assertEquals("From: ReseptienAinesosat line: 49", maito, reseptienAinesosat1.anna(2)); 
    fail("ReseptienAinesosat: 49 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    reseptienAinesosat1.lisaa(maito); assertEquals("From: ReseptienAinesosat line: 50", 3, reseptienAinesosat1.getLkm()); 
    reseptienAinesosat1.lisaa(maito); assertEquals("From: ReseptienAinesosat line: 51", 4, reseptienAinesosat1.getLkm()); 
    reseptienAinesosat1.lisaa(maito); assertEquals("From: ReseptienAinesosat line: 52", 5, reseptienAinesosat1.getLkm()); 
    reseptienAinesosat1.lisaa(maito); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaReseptinAinesosat108 */
  @Test
  public void testAnnaReseptinAinesosat108() {    // ReseptienAinesosat: 108
    ReseptienAinesosat reseptienAinesosat = new ReseptienAinesosat(); 
    ReseptinAinesosa maito = new ReseptinAinesosa(); 
    maito.testiReseptinAinesosa(); 
    ReseptinAinesosa hiiva = new ReseptinAinesosa(); 
    ReseptinAinesosa maito2 = new ReseptinAinesosa(); 
    maito2.testiReseptinAinesosa(); 
    try {
    reseptienAinesosat.lisaa(maito); 
    reseptienAinesosat.lisaa(hiiva); 
    reseptienAinesosat.lisaa(maito2); 
    } catch (SailoException ex) {
    System.out.println(ex.getMessage()); 
    }
    int[] t = reseptienAinesosat.annaReseptinAinesosat(1); 
    assertEquals("From: ReseptienAinesosat line: 124", "[1, 1]", Arrays.toString(t)); 
  } // Generated by ComTest END
}