package ruokaVinkki.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import java.util.*;
import ruokaVinkki.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.11.29 17:29:47 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class RuokaVinkkiTest {



  // Generated by ComTest BEGIN
  /** testAnnaAinesosat111 */
  @Test
  public void testAnnaAinesosat111() {    // RuokaVinkki: 111
    RuokaVinkki ruokaVinkki = new RuokaVinkki(); 
    try {
    Resepti nakkijuustosarvet = new Resepti(); 
    Resepti makaroni = new Resepti(); 
    nakkijuustosarvet.rekisteroi(); 
    nakkijuustosarvet.testiResepti(); 
    makaroni.rekisteroi(); 
    ruokaVinkki.lisaa(nakkijuustosarvet); 
    ruokaVinkki.lisaa(makaroni); 
    Ainesosa maito = new Ainesosa(); 
    maito.rekisteroi(); 
    maito.testiAinesosa(); 
    Ainesosa hiiva = new Ainesosa(); 
    hiiva.rekisteroi(); 
    ruokaVinkki.lisaa(maito); 
    ruokaVinkki.lisaa(hiiva); 
    ReseptinAinesosa maitoLiitetty = new ReseptinAinesosa(); 
    maitoLiitetty.testiReseptinAinesosa(); 
    ruokaVinkki.lisaa(maitoLiitetty); 
    List<Ainesosa> lista = new ArrayList<Ainesosa>(); 
    lista = ruokaVinkki.annaAinesosat(1); 
    assertEquals("From: RuokaVinkki line: 135", 1, lista.size()); 
    } catch (SailoException ex) {
    System.out.println(ex.getMessage()); 
    }
  } // Generated by ComTest END
}